import { CanvasDirection, GlobalCompositeOperation, ImageSmoothingQuality, LineCap, LineJoin, TextAlign, TextBaseline } from "../../src";

export interface ISaveRestoreTestSuite {
  getDirection(): CanvasDirection;
  getFillStyle(): number;
  getFilter(): number;
  getFont(): number;
  getGlobalAlpha(): number;
  getGlobalCompositeOperation(): GlobalCompositeOperation;
  getImageSmoothingEnabled(): number;
  getImageSmoothingQuality(): ImageSmoothingQuality;
  getLineCap(): LineCap;
  getLineDashOffset(): number;
  getLineJoin(): LineJoin;
  getLineWidth(): number;
  getMiterLimit(): number;
  getShadowBlur(): number;
  getShadowColor(): number;
  getShadowOffsetX(): number;
  getShadowOffsetY(): number;
  getTransform(): number;
  hardSave(): void;
  init(): void;
  restore(): void;
  save(): void;
  setDirection(value: CanvasDirection): void;
  setFillStyle(value: number): void;
  setFilter(value: number): void;
  setFont(font: number): void;
  setGlobalAlpha(value: number): void;
  setGlobalCompositeOperation(value: GlobalCompositeOperation): void;
  setImageSmoothingEnabled(value: number): void;
  setImageSmoothingQuality(value: ImageSmoothingQuality): void;
  setLineCap(value: LineCap): void;
  setLineDashOffset(value: number): void;
  setLineJoin(value: LineJoin): void;
  setLineWidth(value: number): void;
  setMiterLimit(value: number): void;
  setShadowBlur(value: number): void;
  setShadowColor(value: number): void;
  setShadowOffsetX(value: number): void;
  setShadowOffsetY(value: number): void;
  setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void;
  getStrokeStyle(): number;
  setStrokeStyle(value: number): void;
  getTextAlign(): TextAlign;
  setTextAlign(value: TextAlign): void;
  getTextBaseline(): TextBaseline;
  setTextBaseline(value: TextBaseline): void;
}
