export enum GlobalCompositeOperation {
  source_over = 0,
  source_in = 1,
  source_out = 2,
  source_atop = 3,
  destination_over = 4,
  destination_in = 5,
  destination_out = 6,
  destination_atop = 7,
  lighter = 8,
  copy = 9,
  xor = 10,
  multiply = 11,
  screen = 12,
  overlay = 13,
  darken = 14,
  lighten = 15,
  color_dodge = 16,
  color_burn = 17,
  hard_light = 18,
  soft_light = 19,
  difference = 20,
  exclusion = 21,
  hue = 22,
  saturation = 23,
  color = 24,
  luminosity = 25,
}
